spring:
  config:
    import:
      - classpath:notification.yml
      - classpath:database.yml
      - classpath:monitoring.yml
      - classpath:oauth.yml
      - classpath:payment.yml

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/seed

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

springdoc:
  api-docs:
    path: /v3/api-docs
    version: OPENAPI_3_0
  swagger-ui:
    tags-sorter: alpha
    enabled: true
    path: /swagger
  default-produces-media-type: application/json

logging:
  level:
    com.sportsify: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
