spring:
  application:
    name: sportsify
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jackson:
    time-zone: UTC
    datatype:
      datetime:
        write-dates-as-timestamps: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger
  default-produces-media-type: application/json