spring:
  config:
    import:
      - classpath:notification.yml
      - classpath:database.yml
      - classpath:monitoring.yml
      - classpath:oauth.yml
      - classpath:payment.yml
      - classpath:notification-local.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:sportsify}
    username: ${DB_USERNAME:sportsify}
    password: ${DB_PASSWORD:sportsify}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      # password 없음 (로컬)

springdoc:
  api-docs:
    path: /v3/api-docs
    version: OPENAPI_3_0
  swagger-ui:
    tags-sorter: alpha
    enabled: true
    path: /swagger
  default-produces-media-type: application/json

logging:
  level:
    com.sportsify: DEBUG

