### 액세스 토큰 갱신
POST http://localhost:8080/api/auth/token/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

> {%
  client.test("2xx/3xx", function() { client.assert(response.status >= 200 && response.status < 400, "status: " + response.status); });
  client.global.set("accessToken", response.body.accessToken);
  client.global.set("refreshToken", response.body.refreshToken);
%}

### 로그아웃
POST http://localhost:8080/api/auth/logout
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

> {%
  client.test("2xx/3xx", function() { client.assert(response.status >= 200 && response.status < 400, "status: " + response.status); });
%}
