package com.sportsify.chat.domain.model.event;

public enum EventType {
    TYPING, MESSAGE_SENT, MESSAGE_DELETED, READ_RECEIPT, READ_UPDATED,
    MEMBER_JOINED, MEMBER_LEFT, MEMBER_INVITED, MEMBER_BANNED,
    ROOM_UPDATED, ROOM_DELETED, ROOM_ARCHIVED, ROOM_UNARCHIVED
}
